# Generated by Django 4.1 on 2023-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_mymodel_option1_remove_mymodel_option2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='q5',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='q1',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='Red', max_length=50),
        ),
    ]
