# Generated by Django 4.1 on 2023-04-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mymodel_q2_alter_mymodel_q1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='q2',
        ),
    ]
